#include "EvmScanPage.h"
#include <QPixmap>
#include <QPainter>
#include <QPainterPath>
#include <QMessageBox>
#include <QDateTime>
#include <QBuffer>

EvmScanPage::EvmScanPage(QWidget *parent) : QWidget(parent) {
    lastProcessTime = 0;
    scanAlreadySuccessful = false;
    setupUi();
    startCamera();
}

EvmScanPage::~EvmScanPage() {
    if (camera) camera->stop();
}

void EvmScanPage::setupUi() {
    this->setObjectName("ScanPageBG");
    this->setStyleSheet("#ScanPageBG { background-color: #f5f7fb; }");
    QVBoxLayout *mainLayout = new QVBoxLayout(this);
    mainLayout->setContentsMargins(0, 0, 0, 0); // Flush to edges
    mainLayout->setSpacing(0);

    // ==========================================
    // 1. TOP BAR (Red/Black Gradient & Circular Logo)
    // ==========================================
    QFrame *topBar = new QFrame(this);
    topBar->setFixedHeight(80);
    topBar->setStyleSheet("QFrame { background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #580000, stop:1 #101010); border: none; }");

    QHBoxLayout *topBarLayout = new QHBoxLayout(topBar);
    topBarLayout->setContentsMargins(20, 10, 20, 10);

    // Make the circular logo
    logoLabel = new QLabel(this);
    logoLabel->setFixedSize(50, 50);
    logoLabel->setStyleSheet("background: transparent;"); // Prevent gradient interference

    // Load and mask the image into a circle
    QPixmap originalLogo(":/resource/pak.evm-logo.png"); // CHANGE THIS TO YOUR RESOURCE PATH!
    if (!originalLogo.isNull()) {
        QPixmap circularLogo(50, 50);
        circularLogo.fill(Qt::transparent);
        QPainter painter(&circularLogo);
        painter.setRenderHint(QPainter::Antialiasing);
        QPainterPath path;
        path.addEllipse(0, 0, 50, 50);
        painter.setClipPath(path);
        painter.drawPixmap(0, 0, 50, 50, originalLogo);
        logoLabel->setPixmap(circularLogo);
    } else {
        // Fallback if image fails to load
        logoLabel->setStyleSheet("background-color: white; border-radius: 25px;");
    }

    QLabel *titleLabel = new QLabel("PAK.EVM", this);
    titleLabel->setStyleSheet("font-size: 28px; font-weight: 900; color: white; letter-spacing: 2px; background: transparent;");

    timeRemainingLabel = new QLabel("Time Remaining: 00:00:00", this);
    timeRemainingLabel->setStyleSheet("font-size: 20px; font-weight: bold; color: white; background: transparent; padding-right: 20px;");

    topBarLayout->addWidget(logoLabel);
    topBarLayout->addSpacing(15);
    topBarLayout->addWidget(titleLabel);
    topBarLayout->addStretch(200);
    topBarLayout->addWidget(timeRemainingLabel);
    topBarLayout->addStretch();

    mainLayout->addWidget(topBar);

    // ==========================================
    // 2. MAIN BODY (Split Layout)
    // ==========================================
    QHBoxLayout *bodyLayout = new QHBoxLayout();
    bodyLayout->setContentsMargins(50, 50, 50, 50);
    bodyLayout->setSpacing(50);

    // --- LEFT SIDE: INSTRUCTIONS ---
    QVBoxLayout *leftLayout = new QVBoxLayout();

    QLabel *instructionTitle = new QLabel("Verify Your Identity", this);
    instructionTitle->setStyleSheet("font-size: 36px; font-weight: bold; color: #2C3E50; background: transparent;");

    QLabel *instructionDesc = new QLabel(
        "To cast your ballot, you must present the secure digital token generated by the Registration Portal.\n\n"
        "1. Open the PAK.EVM app on your mobile device.\n"
        "2. Navigate to 'My Tokens' and open today's Election Token.\n"
        "3. Hold your phone screen up to the camera on the right.\n"
        "4. Keep the QR code steady inside the rectangular frame.", this);
    instructionDesc->setWordWrap(true);
    instructionDesc->setStyleSheet(
        "font-size: 20px; "             /* Restores your large font */
        "color: #34495E; "              /* Dark grey text */
        "line-height: 1.8; "            /* Spacing between lines */
        "margin-top: 20px; "            /* Pushes it down from the title */
        "background: transparent; "     /* Lets the grey page background show through */
        "border: 2px solid #580000; "   /* Your dark red theme border! */
        "border-radius: 12px; "         /* Rounded corners */
        "padding: 20px;"                /* CRITICAL: Keeps text away from the red border */
        );
    QLabel *cnicLabel = new QLabel("Enter your CNIC:", this);
    cnicLabel->setStyleSheet("font-size: 18px; font-weight: bold; color: #2C3E50; margin-top: 30px;");

    cnicInput = new QLineEdit(this);
    cnicInput->setPlaceholderText("e.g., 42101-1234567-1");
    cnicInput->setStyleSheet("QLineEdit { border: 2px solid #BDC3C7; border-radius: 8px; padding: 15px; font-size: 20px; background-color: white; color: #2C3E50; }"
                             "QLineEdit:focus { border: 2px solid #7A1A1A; }");

    leftLayout->addWidget(instructionTitle);
    leftLayout->addWidget(instructionDesc);
    leftLayout->addWidget(cnicLabel);
    leftLayout->addWidget(cnicInput);
    leftLayout->addStretch();

    // --- RIGHT SIDE: CAMERA & RED BOX ---
    QVBoxLayout *rightLayout = new QVBoxLayout();
    rightLayout->setAlignment(Qt::AlignCenter);

    // Camera Frame (The rectangular box)
    QFrame *cameraFrame = new QFrame(this);
    cameraFrame->setFixedSize(400, 400);
    cameraFrame->setStyleSheet("QFrame { background-color: black; border: 4px dashed #3498DB; border-radius: 12px; }");
    QVBoxLayout *cameraLayout = new QVBoxLayout(cameraFrame);
    cameraLayout->setContentsMargins(5, 5, 5, 5);

    videoWidget = new QVideoWidget(cameraFrame);
    videoWidget->setStyleSheet("border-radius: 8px;"); // Ensure video fits cleanly
    cameraLayout->addWidget(videoWidget);

    // Status Label
    scanStatusLabel = new QLabel("Waiting for QR Code...", this);
    scanStatusLabel->setAlignment(Qt::AlignCenter);
    scanStatusLabel->setStyleSheet("font-size: 18px; font-weight: bold; color: #7F8C8D; margin-top: 15px;");

    // The Red Proceed Button
    proceedBtn = new QPushButton("Proceed to Voting ➔", this);
    proceedBtn->setCursor(Qt::PointingHandCursor);
    proceedBtn->setFixedSize(400, 60);

    // Disabled style by default!
    proceedBtn->setEnabled(false);
    proceedBtn->setStyleSheet(
        "QPushButton { background-color: #BDC3C7; color: white; border-radius: 8px; font-size: 20px; font-weight: bold; }"
        "QPushButton:disabled { background-color: #BDC3C7; color: #ECF0F1; }"
        );
    connect(proceedBtn, &QPushButton::clicked, this, &EvmScanPage::onProceedClicked);

    // Simulate Scan Button (For development testing)
    QPushButton *simBtn = new QPushButton("Simulate Scan (Dev)", this);
    simBtn->setStyleSheet("color: blue; border: none; text-decoration: underline; margin-top: 20px;");
    connect(simBtn, &QPushButton::clicked, this, &EvmScanPage::simulateSuccessfulScan);

    rightLayout->addWidget(cameraFrame);
    rightLayout->addWidget(scanStatusLabel);
    rightLayout->addSpacing(20);
    rightLayout->addWidget(proceedBtn);
    rightLayout->addWidget(simBtn, 0, Qt::AlignHCenter); // Dev tool
    rightLayout->addStretch();

    // --- ASSEMBLE ---
    bodyLayout->addLayout(leftLayout, 1);
    bodyLayout->addLayout(rightLayout, 1);
    mainLayout->addLayout(bodyLayout);
}

// ==========================================
// 3. CAMERA LOGIC
// ==========================================
void EvmScanPage::startCamera() {
    // Check if a camera is attached to the computer
    const QList<QCameraDevice> cameras = QMediaDevices::videoInputs();
    if (cameras.isEmpty()) {
        scanStatusLabel->setText("Error: No camera detected.");
        scanStatusLabel->setStyleSheet("font-size: 18px; font-weight: bold; color: #E74C3C; margin-top: 15px; background: transparent;");
        return;
    }

    // Connect the default camera to the video widget
    camera = new QCamera(cameras.first(), this);
    captureSession = new QMediaCaptureSession(this);
    captureSession->setCamera(camera);
    captureSession->setVideoOutput(videoWidget);

    QVideoSink *sink = videoWidget->videoSink();
    connect(sink, &QVideoSink::videoFrameChanged, this,
            &EvmScanPage::onVideoFrameChanged);

    // Start streaming!
    camera->start();
}

void EvmScanPage::stopCamera() {
    if (camera && camera->isActive()) {
        camera->stop();
    }
}

void EvmScanPage::resetScanner() {
    // 1. Reset the logic flags
    scanAlreadySuccessful = false;

    // 2. Clear the inputs
    if (cnicInput) cnicInput->clear();

    // 3. Reset the labels and borders back to Blue/Waiting
    scanStatusLabel->setText("Waiting for QR Code...");
    scanStatusLabel->setStyleSheet("font-size: 18px; font-weight: bold; color: #7F8C8D; margin-top: 15px;");
    videoWidget->parentWidget()->setStyleSheet("QFrame { background-color: black; border: 4px dashed #3498DB; border-radius: 12px; }");

    // 4. Lock the Proceed button again
    proceedBtn->setEnabled(false);
    proceedBtn->setStyleSheet(
        "QPushButton { background-color: #BDC3C7; color: white; border-radius: 8px; font-size: 20px; font-weight: bold; }"
        "QPushButton:disabled { background-color: #BDC3C7; color: #ECF0F1; }"
        );

    // 5. Turn the camera back on!
    startCamera();
}

void EvmScanPage::onVideoFrameChanged(const QVideoFrame &frame) {
    if (scanAlreadySuccessful) return;

    QString cnic = cnicInput->text().trimmed();

    if (cnic.isEmpty()) {
        return;
    }

    // Throttle to 2 frames per second
    qint64 currentTime = QDateTime::currentMSecsSinceEpoch();
    if (currentTime - lastProcessTime < 500) {
        return;
    }
    lastProcessTime = currentTime;

    QImage image = frame.toImage();

    if (!image.isNull()) {
        // ==========================================
        // CONVERT QIMAGE TO BASE64 QSTRING
        // ==========================================
        QByteArray byteArray;
        QBuffer buffer(&byteArray);
        buffer.open(QIODevice::WriteOnly);

        // Save as JPG to keep the string smaller and processing faster
        image.save(&buffer, "JPG", 80);

        QString base64Str = QString(byteArray.toBase64());

        // Emit the String to the Backend Developer!
        emit frameReadyForBackend(base64Str, cnic);
    }
}

// The Backend Developer calls this when their decryption succeeds!
void EvmScanPage::markScanSuccessful(const QString &decryptedTokenData) {
    scanAlreadySuccessful = true; // Stops the camera from sending more images

    // Update the UI
    scanStatusLabel->setText("✅ Token Successfully Scanned!");
    scanStatusLabel->setStyleSheet("font-size: 20px; font-weight: bold; color: #27AE60; margin-top: 15px;");
    videoWidget->parentWidget()->setStyleSheet("QFrame { background-color: black; border: 4px solid #27AE60; border-radius: 12px; }");

    proceedBtn->setEnabled(true);
    proceedBtn->setStyleSheet("QPushButton { background-color: #580000; color: white; border-radius: 8px; font-size: 20px; font-weight: bold; }"
                              "QPushButton:hover { background-color: #7A1A1A; box-shadow: 0px 4px 10px rgba(0,0,0,0.3); }");

    // (Optional) You can print the decrypted data just to verify it worked:
    // qDebug() << "Decrypted Token:" << decryptedTokenData;
}

// (Keep your simulateSuccessfulScan() function. Change its body to just call markScanSuccessful("mock-data"); )
void EvmScanPage::simulateSuccessfulScan() {
    markScanSuccessful("MOCK_SIMULATED_TOKEN_123");
}

void EvmScanPage::updateTimeRemaining(const QString &timeString) {
    timeRemainingLabel->setText("Time Remaining: " + timeString);
}

void EvmScanPage::onProceedClicked() {
    emit proceedToVotingClicked();
}
